2回目の更新を実施した
jane1210jane/ichiyasaGitSample pull request #1
Opened 2023-11-19 06:53 UTC by jane1210jane

##会場について
　２に変更

2023-11-19 07:27 UTC, jane1210jane commented
##確認お願いします
プルリクエストのテスト１回目

2023-11-19 07:43 UTC, yasu1210 commented on index.html
> +                        <p>株式会社インプレイス イベントセミナー会場2です</p>
素晴らしい変更です

2023-11-19 07:44 UTC, yasu1210 requested changes
直してください

2023-11-19 07:44 UTC, yasu1210 commented on index.html
> +                        <p>株式会社インプレイス イベントセミナー会場2です</p>
再度練り直して下さい(錯乱)

2023-11-20 01:46 UTC, yasu1210 approved these changes

2023-11-20 01:59 UTC, merged